// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_create_index
Rcpp::List cpp_create_index(Rcpp::CharacterVector files, std::string type);
RcppExport SEXP _fastqindexr_cpp_create_index(SEXP filesSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_create_index(files, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_read_fqi_index
Rcpp::List cpp_read_fqi_index(Rcpp::CharacterVector fqi_files, Rcpp::CharacterVector files, std::string type);
RcppExport SEXP _fastqindexr_cpp_read_fqi_index(SEXP fqi_filesSEXP, SEXP filesSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type fqi_files(fqi_filesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_read_fqi_index(fqi_files, files, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_restore_index_ptr
SEXP cpp_restore_index_ptr(Rcpp::List index_payload);
RcppExport SEXP _fastqindexr_cpp_restore_index_ptr(SEXP index_payloadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type index_payload(index_payloadSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_restore_index_ptr(index_payload));
    return rcpp_result_gen;
END_RCPP
}
// cpp_index_ptr_is_valid
bool cpp_index_ptr_is_valid(SEXP index_ptr);
RcppExport SEXP _fastqindexr_cpp_index_ptr_is_valid(SEXP index_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type index_ptr(index_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_index_ptr_is_valid(index_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extract_sequences
Rcpp::List cpp_extract_sequences(Rcpp::CharacterVector files, std::string type, Rcpp::NumericVector ids_zero_based, SEXP index_ptr_sexp, bool include_qual);
RcppExport SEXP _fastqindexr_cpp_extract_sequences(SEXP filesSEXP, SEXP typeSEXP, SEXP ids_zero_basedSEXP, SEXP index_ptr_sexpSEXP, SEXP include_qualSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ids_zero_based(ids_zero_basedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index_ptr_sexp(index_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< bool >::type include_qual(include_qualSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract_sequences(files, type, ids_zero_based, index_ptr_sexp, include_qual));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extract_sequences_to_file
double cpp_extract_sequences_to_file(Rcpp::CharacterVector files, std::string source_type, Rcpp::NumericVector ids_zero_based, SEXP index_ptr_sexp, std::string output_type, std::string outfile, bool append, bool compress);
RcppExport SEXP _fastqindexr_cpp_extract_sequences_to_file(SEXP filesSEXP, SEXP source_typeSEXP, SEXP ids_zero_basedSEXP, SEXP index_ptr_sexpSEXP, SEXP output_typeSEXP, SEXP outfileSEXP, SEXP appendSEXP, SEXP compressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type source_type(source_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ids_zero_based(ids_zero_basedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index_ptr_sexp(index_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_type(output_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type outfile(outfileSEXP);
    Rcpp::traits::input_parameter< bool >::type append(appendSEXP);
    Rcpp::traits::input_parameter< bool >::type compress(compressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract_sequences_to_file(files, source_type, ids_zero_based, index_ptr_sexp, output_type, outfile, append, compress));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extract_sequences_dnastringset
SEXP cpp_extract_sequences_dnastringset(Rcpp::CharacterVector files, std::string source_type, Rcpp::NumericVector ids_zero_based, SEXP index_ptr_sexp, double chunk_chars, std::string renumber_mode);
RcppExport SEXP _fastqindexr_cpp_extract_sequences_dnastringset(SEXP filesSEXP, SEXP source_typeSEXP, SEXP ids_zero_basedSEXP, SEXP index_ptr_sexpSEXP, SEXP chunk_charsSEXP, SEXP renumber_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type source_type(source_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ids_zero_based(ids_zero_basedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index_ptr_sexp(index_ptr_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type chunk_chars(chunk_charsSEXP);
    Rcpp::traits::input_parameter< std::string >::type renumber_mode(renumber_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extract_sequences_dnastringset(files, source_type, ids_zero_based, index_ptr_sexp, chunk_chars, renumber_mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastqindexr_cpp_create_index", (DL_FUNC) &_fastqindexr_cpp_create_index, 2},
    {"_fastqindexr_cpp_read_fqi_index", (DL_FUNC) &_fastqindexr_cpp_read_fqi_index, 3},
    {"_fastqindexr_cpp_restore_index_ptr", (DL_FUNC) &_fastqindexr_cpp_restore_index_ptr, 1},
    {"_fastqindexr_cpp_index_ptr_is_valid", (DL_FUNC) &_fastqindexr_cpp_index_ptr_is_valid, 1},
    {"_fastqindexr_cpp_extract_sequences", (DL_FUNC) &_fastqindexr_cpp_extract_sequences, 5},
    {"_fastqindexr_cpp_extract_sequences_to_file", (DL_FUNC) &_fastqindexr_cpp_extract_sequences_to_file, 8},
    {"_fastqindexr_cpp_extract_sequences_dnastringset", (DL_FUNC) &_fastqindexr_cpp_extract_sequences_dnastringset, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastqindexr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
