# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_create_index <- function(files, type) {
    .Call(`_fastqindexr_cpp_create_index`, files, type)
}

cpp_extract_sequences <- function(files, type, ids_zero_based, index_token) {
    .Call(`_fastqindexr_cpp_extract_sequences`, files, type, ids_zero_based, index_token)
}

