# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_create_index <- function(files, type) {
    .Call(`_fastqindexr_cpp_create_index`, files, type)
}

cpp_read_fqi_index <- function(fqi_files, files, type) {
    .Call(`_fastqindexr_cpp_read_fqi_index`, fqi_files, files, type)
}

cpp_restore_index_ptr <- function(index_payload) {
    .Call(`_fastqindexr_cpp_restore_index_ptr`, index_payload)
}

cpp_index_ptr_is_valid <- function(index_ptr) {
    .Call(`_fastqindexr_cpp_index_ptr_is_valid`, index_ptr)
}

cpp_extract_sequences <- function(files, type, ids_zero_based, index_ptr_sexp, include_qual, max_bridge_gap, max_region_bytes, extract_mode, diagnostics) {
    .Call(`_fastqindexr_cpp_extract_sequences`, files, type, ids_zero_based, index_ptr_sexp, include_qual, max_bridge_gap, max_region_bytes, extract_mode, diagnostics)
}

cpp_extract_sequences_to_file <- function(files, source_type, ids_zero_based, index_ptr_sexp, output_type, outfile, append, compress, max_bridge_gap, max_region_bytes, extract_mode, diagnostics) {
    .Call(`_fastqindexr_cpp_extract_sequences_to_file`, files, source_type, ids_zero_based, index_ptr_sexp, output_type, outfile, append, compress, max_bridge_gap, max_region_bytes, extract_mode, diagnostics)
}

cpp_extract_sequences_dnastringset <- function(files, source_type, ids_zero_based, index_ptr_sexp, chunk_chars, max_bridge_gap, max_region_bytes, extract_mode, diagnostics, renumber_mode) {
    .Call(`_fastqindexr_cpp_extract_sequences_dnastringset`, files, source_type, ids_zero_based, index_ptr_sexp, chunk_chars, max_bridge_gap, max_region_bytes, extract_mode, diagnostics, renumber_mode)
}

